feat: lighthouse ci

diff --git a/.github/workflows/lighthouse-demo.yml b/.github/workflows/lighthouse-demo.yml
--- a/.github/workflows/lighthouse-demo.yml
+++ b/.github/workflows/lighthouse-demo.yml
@@ -1,13 +1,22 @@
 name: CI
 on: [push]
 jobs:
-  lighthouseci:
+  lhci:
+    name: Lighthouse CI
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
-      - uses: actions/setup-node@v1
-      - run: npm install && npm install -g @lhci/cli@0.9.x
-      - run: npm run build
-      - run: lhci autorun
+      - uses: actions/checkout@v1
+      - name: Use Node.js
+        uses: actions/setup-node@v1
+        with:
+          node-version: 12.x
+      - name: npm install, build
+        run: |
+          yarn
+          npm run build
+      - name: run lighthouse-ci
+        run: |
+          npm install -g @lhci/cli@0.3.x
+          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
         env:
-          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
+          LHCI_GITHUB_APP_TOKEN: ${{secrets.LHCI_GITHUB_APP_TOKEN}}
